name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run NX Affected
        run: nx affected --base=main --head=HEAD

      - run: bun install
      - uses: nrwl/nx-set-shas@v4

      - run: bunx nx-cloud start-ci-run --distribute-on="5 linux-medium-js"
      - run: npx nx-cloud record -- nx format:check
      - run: bun nx affected -t lint build
