name: CI

on:
  pull_request:
    types:
      - "labeled"
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    if: "${{ github.event.label.name == 'Cloud' }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - uses: nrwl/nx-set-shas@v4

      - run: bun nx affected -t lint build
